name: deploy-to-server
on:
  push:
    branches:
      - main
jobs:
  Upload-to-SFTP:
    runs-on: ubuntu-latest
    #timeout-minutes: 30
    steps:
      - name: 🚚 Get latest code                        # Checkout the latest code
        uses: actions/checkout@v4
        with:
          clean: 'true'
          show-progress: 'true'

      - name: FTP Clean First
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          # FTP host
          host: ${{ secrets.HOST }}
          # FTP user
          user: ${{ secrets.USER }}
          # FTP password
          password: ${{ secrets.PASS }}
          # Remote files separated by ; (wildcards accepted)
          remoteFiles: '*.html' # default is 
          # Directories to delete seperated by ";"
          remoteDirectories: 'assets;content;data;functions;models' # optional, default is 
          # Working directory
          workingDir: '/domains/futurecx.nl/public_html' # optional, default is /
          # Ignore invalid TLS/SSL certificate (1=ignoreSSL)
          ignoreSSL: '1' # optional, default is 0
          # Additional command-line options for lftp
          options: '' # optional, default is
        
      - name: 📂 ftp-action
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          # FTP host
          host: ${{ secrets.HOST }}
          # FTP user
          user: ${{ secrets.USER }}
          # FTP password
          password: ${{ secrets.PASS }}
          # Force SSL encryption
          forceSsl: false
          # Local directory
          localDir: '.'
          # Remote directory
          remoteDir: '/domains/futurecx.nl/public_html'

      - name: FTP Cleanup After
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          # FTP host
          host: ${{ secrets.HOST }}
          # FTP user
          user: ${{ secrets.USER }}
          # FTP password
          password: ${{ secrets.PASS }}
          # Remote files separated by ; (wildcards accepted)
          remoteFiles: '.babelrc.js;.browserslistrc;.editorconfig;.eslintignore;.eslintrc.js;.gitignore;.htmlvalidate.json;.prettierrc;.stylelintrc.json;gulpfile.js;package-lock.json;package.json;next-sitemap.config.js;next-sitemap.js;rmcmd;README.md' # default is 
          # Directories to delete seperated by ";"
          remoteDirectories: '.github;cgi-bin' # optional, default is 
          # Working directory
          workingDir: '/domains/futurecx.nl/public_html' # optional, default is /
          # Ignore invalid TLS/SSL certificate (1=ignoreSSL)
          ignoreSSL: '1' # optional, default is 0
          # Additional command-line options for lftp
          options: '' # optional, default is

      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
