name: deploy-to-server
on:
  push:
    branches:
      - main
jobs:
  Upload-to-SFTP:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code                        # Checkout the latest code
        uses: actions/checkout@v2
        
      - name: 📂 ftp-action
        uses: Future-CX/Futurecx-nl@v1
        with:
          # FTP host
          host: ${{ secrets.HOST }}
          # FTP user
          user: ${{ secrets.USER }}
          # FTP password
          password: ${{ secrets.PASS }}
          # Force SSL encryption
          forceSsl: false
          # Local directory
          localDir: '.'
          # Remote directory
          remoteDir: '/domains/futurecx.nl/public_html'
