name: deploy-to-server
on:
  push:
    branches:
      - main
jobs:
  Upload-to-SFTP:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code                        # Checkout the latest code
        uses: actions/checkout@v3
        
      
